server:
  port: 5555
spring:
  application:
    name: api-gateway
eureka:
  client:
    service-url:
      defaultZone: http://service1:8081/eureka/,http://service2:8082/eureka/
#zuul:
#  routes:
#    baidu: 
#      path: /test/**
#      url: http://www.163.com/
zuul:
  routes:
    ribbonurl:
      path: /ribbon/**
      serviceId: HELLO-SERVICE
    feignurl: 
      path: /feign/**
      serviceId: FEIGN-CONSUMER