server:
  port: 9000
  
spring:
  application:
    name: ribbon-consumer

eureka:
  client:
    service-url:
      defaultZone: http://service1:8081/eureka/
      
#hello-service: 
#  ribbon: 
#    NFLoadBalancerRuleClassName: com.netflix.loadbalancer.RandomRule