server:
  port: 7001
spring:
  application:
    name: config-server
  cloud:
    config:
      label: master
      server:
        git:
          uri: https://github.com/namelessAJ/springcloud.git
          search-paths: /microservice/configs
          username: 
          password: 
eureka:
  client:
    service-url:
      defaultZone: http://service1:8081/eureka/,http://service2:8082/eureka/